# Comprehensive Grafana Dashboard Configuration

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    
  - name: Elasticsearch
    type: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    database: parking-logs-*
    timeField: "@timestamp"

  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
